### ISSUE TITLE
Use `--parameter=value` over `--parameter value` for dragen workflows

### ISSUE THREAD

**Issue by alexiswl** [umccr/cwl-ica#264]
See 

```
ica-context-switcher --project production
gds-view \
  --gds-path gds://production/analysis_data/SBJ03077/wgs_tumor_normal/202301297967f74d/L2300124_L2300123_dragen/PRJ230040-replay.json \
  --to-stdout | \
jq --raw-output \
  '
    .command_line=(
      .command_line | split(" ")
     ) | 
    .dragen_config=(
      .dragen_config | 
      map(
        {
           "key": .name, 
           "value": .value
        }
      ) | 
      from_entries
    )
  ' | 
yq --prettyPrint
```

for yields

```
command_line:
  - /opt/edico/bin/dragen
  - --enable-variant-caller
  - "true"
  - --intermediate-results-dir
  - /ephemeral/intermediate-results/
  - --enable-duplicate-marking
  - "true"
  - --enable-map-align-output
  - "true"
  - --enable-sv
  - "true"
  - --fastq-list
  - fastq_list.csv
  - --lic-instance-id-location
  - /opt/instance-identity
  - --output-directory
  - L2300124_L2300123_dragen
  - --output-file-prefix
  - PRJ230040
  - --ref-dir
  - /ephemeral/ref/hg38-v8-altaware-cnv-anchored/
  - --tumor-fastq-list
  - tumor_fastq_list.csv
hash_table_build:
  sw_version: 01.003.044.3.5.3-38-gefdaeaff
  hash_table_version: "8"
  command_line_options: /opt/edico/bin/dragen --lic-instance-id-location /root/.edico --build-hash-table true --ht-reference /data/input/appresults/217816899/hg38.fa --ht-alt-liftover /opt/edico/liftover/bwa-kit_hs38DH_liftover.sam --ht-build-rna-hashtable true --enable-cnv true --ht-alt-aware-validate true --output-directory /data/scratch/hg38_altaware
dragen_config:
  Aligner.align-direction: "4"
  Aligner.aln-en-mask: "15"
  Aligner.aln-enable: "1"
  Aligner.backtrace-delay: "8"
  Aligner.bed-score-bonus: "0"
  Aligner.chicken: "0"
...
```

This seems petty, but would be much easier to query if we can just search for `--enable-sv=true` as an argument.  

Will mean converting inputBinding arguments for booleans from

```yaml
inputBinding:
  prefix: --my-parameter
  valueFrom: "$(self.toString())"
```

which yields

`--my-parameter "true" `  OR `--my-parameter "false"`

to
```yaml		
inputBinding:
  prefix: --my-parameter=
  separate: false
  valueFrom: "$(self.toString())"
```

`--my-parameter="true"` OR `--my-parameter="false"`
