### ISSUE TITLE
Running into out of memory issue with qualimap

### ISSUE THREAD

**Issue by skanwal** [umccr/cwl-ica#268]
One of my recent WTS workflow runs have failed with following error:

```
$ gds-view --gds-path gds://development/temp/alexis/parameter_name_test/work/20230208_123757/logs/run_qualimap_step/try-1/task-stdouterr-0.log --to-stdout
Java memory size is set to 96G
Launching application...

detected environment java options -Djava.io.tmpdir=/scratch
QualiMap v.2.2.2-dev
Built on 2019-11-11 14:05

Selected tool: rnaseq
Initializing regions from /data/cwl-stage-dir/stg6377bf94-eada-4294-b07b-c45af51c6be1/ref-transcripts.non-zero-length.gtf...

Initialized 100000 regions...
Initialized 200000 regions...
Initialized 300000 regions...
Initialized 400000 regions...
Initialized 500000 regions...
Initialized 600000 regions...
Initialized 700000 regions...
Initialized 800000 regions...
Initialized 900000 regions...
Initialized 1000000 regions...
Initialized 1100000 regions...
Initialized 1200000 regions...
Initialized 1300000 regions...
Initialized 1400000 regions...

WARNING: out of memory!
Qualimap allows to set RAM size using special argument: --java-mem-size
Check more details using --help command or read the manual.
```

This has happened after resource requirements were updated for various tools including qualimap https://github.com/umccr/cwl-ica/commit/ca866a43bc716051ee2c7d037edde276bac0588a. The workflow however is setting java heap memory size to 96G https://github.com/umccr/cwl-ica/blob/main/workflows/dragen-transcriptome-pipeline/3.9.3/dragen-transcriptome-pipeline__3.9.3.cwl#L129, which causes above error. 

**Solution:**

Need to update workflow definition to set java memory according to resource requirements being set in the tool definition and test if it works with standard-large compute.

**Comment by skanwal** [comment]
Based on the comment here, https://github.com/umccr/cwl-ica/issues/240 "Highest observed Max Mem Usage for all qualimap tasks is 12 Gb.", I tried setting java mem size to 24G but that still errored out. Not sure why isn't this being correctly reflected in the calculations.

We might need to bump up the image to standard xlarge.

**Comment by alexiswl** [comment]
Thanks for looking into this @skanwal, looking back, I was wondering why I chose a standard large instance (since in the [ICAv1 docs](https://illumina.gitbook.io/ica-v1/analysis/a-taskexecution#type-and-size) standard large is 2 CPU and 7 GB memory.  

But from the error https://github.com/umccr/cwl-ica/issues/240 I have actually linked to the [ICAv2 Page](https://help.ica.illumina.com/project/p-flow/f-pipelines#compute-types) and there standard large is 8 CPUs and 32 GB memory!  

Another important thing to note is that the java-mem-size should be smaller than the overall memory. Can you try set it to "6GB" with the same instance type and see if that works? Otherwise can move to xxlarge instance type, which is the closest to a v2 large instance type

**Comment by alexiswl** [comment]
Will put up an issue in the ICAv2 page for this, it doesn't help with migration :/

**Comment by alexiswl** [comment]
Issue here: https://github.com/umccr-illumina/ica_v2/issues/128

**Comment by skanwal** [comment]
@alexiswl - thanks for opening up the issue. I agree this is a big discrepancy between ICA v1 and v2. I wouldn't have noticed if we had not run into this issue.

Re qualimap java mem - 6GB seems small, also noted in few other [issues](https://www.biostars.org/p/441286/). From the issue#240, we can see few runs used upto 12G of memory. On the safer side, I'd like to bump it up a bit.

**Comment by alexiswl** [comment]
Sure, it may be worth placing these in the `inputBinding` sections or `arguments` sections of the tool rather than in the InitialWorkDirRequirement seciton, will make it easier to see which values have been used from the TES page

**Comment by alexiswl** [comment]
Also with testing, noted this

```
if [[ ! -z "null" ]]
then
  export JAVA_OPTS=-Djava.io.tmpdir="null"
fi
```

So tmpdir may be set to "null" rather than empty

So I'd probably update from 

```yaml
requirements:
  InlineJavascriptRequirement: {}
  InitialWorkDirRequirement:
    listing:
      - entryname: "run_qualimap.sh"
        entry: |
          #!/usr/bin/env bash
          
          # Set to fail
          set -euo pipefail
          
          # Set java opts
          if [[ ! -z "$(inputs.tmp_dir)" ]]
          then
            export JAVA_OPTS=-Djava.io.tmpdir="$(inputs.tmp_dir)"
          fi
          # Run qualimap
          eval qualimap rnaseq --paired --java-mem-size="$(inputs.java_mem)" '"\${@}"'
```

to

```yaml
requirements:
  InlineJavascriptRequirement: {}
  InitialWorkDirRequirement:
    listing:
      - entryname: "run_qualimap.sh"
        entry: |
          #!/usr/bin/env bash
          
          # Set to fail
          set -euo pipefail
          
          # Set java opts
          if [[ ! -z "$(inputs.tmp_dir)" || "$(inputs.tmp_dir)" == "null" ]]; then
            export JAVA_OPTS=-Djava.io.tmpdir="$(inputs.tmp_dir)"
          fi
          
          # Run qualimap
          eval qualimap rnaseq --paired --java-mem-size="$(inputs.java_mem)" '"\${@}"'
```

**Comment by alexiswl** [comment]
> Sure, it may be worth placing these in the inputBinding sections or arguments sections of the tool rather than in the InitialWorkDirRequirement seciton, will make it easier to see which values have been used from the TES page.

This would also change the qualimap line to 

```
eval qualimap rnaseq '"\${@}"'
```

And have the following arguments section

```yaml
arguments:
  - position: -1
    valueFrom: "--paired"
```

With the inputBinding

```yaml
inputs:
    java_mem:
      label: java mem
      doc: |
        Set desired Java heap memory size
      type: string
      inputBinding:
        prefix: "--java-mem-size="
        separate: False
 ```
